[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "policy_transportation"
version = "0.1.0"
description = "Gaussian Process Transportation"
authors = [
  { name = "Giovanni Franzese", email = "g.franzese@tudelft.nl" }
]
license = "MIT" 
requires-python = ">=3.6"
dependencies = [
  "matplotlib",
  "numpy",
  "pandas",
  "pynput",
  "scikit_learn",
  "scipy", 
  "similaritymeasures"
]

[tool.setuptools.packages.find]
include = ["policy_transportation", "policy_transportation.*"]
