# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - 'size' refers to the length of the shared border between solid black and solid white rectangle.
#   See README.md or https://github.com/AprilRobotics/apriltag/wiki/AprilTag-User-Guide#pose-estimation for details.
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
# FOR DRESSING
# standalone_tags:
#   [ 
#   {id: 0, size: 0.0245, name: marker},
#   {id: 1, size: 0.0245},
#   {id: 2, size: 0.0245},
#   {id: 3, size: 0.0245},
#   {id: 4, size: 0.0245},
#   {id: 5, size: 0.0245},
#   {id: 6, size: 0.0245},
#   {id: 7, size: 0.0245},
#   {id: 8, size: 0.0245},
#   ]
# FOR PnP

standalone_tags:
  [ 
  {id: 0, size: 0.033, name: marker},
  {id: 1, size: 0.033},
  {id: 2, size: 0.033},
  {id: 3, size: 0.033},
  {id: 4, size: 0.033},
  {id: 5, size: 0.033},
  {id: 6, size: 0.033},
  {id: 7, size: 0.033},
  {id: 32, size: 0.039},
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
  ]
